on:
  workflow_dispatch: 
    inputs:
      environment:
        description: "Choose Environment"
        required: true
        default: "Staging"
        type: choice
        options:
          - staging
          - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deply Applcation
        run: echo "Deploy application ${{ inputs.environment }}"
